#ifndef FEA_CONTOUR
#define FEA_CONTOUR

#include <opencv2/opencv.hpp>
using namespace cv;
using namespace std;


/**
* @brief ...
* 
* @param visited p_visited:...
* @param img p_img:...
* @param direction p_direction:...
* @param basePoint p_basePoint:...
* @param params p_params:...
* @param score p_score:...
*/
void score_by_contour(Mat& visited, Mat& img,int direction[], Point basePoint, vector<int> params,float* score);
/**
* @brief ...
* 
* @param visited p_visited:...
* @param img p_img:...
* @param direction p_direction:...
* @param basePoint p_basePoint:...
* @param params p_params:...
* @param score p_score:...
*/
void score_by_texture(Mat& visited, Mat& img,int direction[], Point basePoint, vector<int> params,float* score);

#endif
